language: python
script: bash bin/test.sh
deploy:
  provider: pypi
  user: "__token__"
  password:
    secure: Cgmj9DgaDyHKoPcJeIsfZgIMIklZL3/83P1gvvvBGpfmeFwzJ43Xwcqh/dxmES/9F1GQsM1XLbxf9IcOeDbDIHTaQWgXp6PDLT0/7er23UVngmBXkH2CgsLvKshJPI3OCQwEoL2C/EM4R73E0LowpOOIOFHR1xT2yFqIWpzePCoScy8t3FAzEzFlxDQPGb3yhrq4oWZCjLSqlGAvDNcEyW1BMt6GW1LzBALNJ4JuiZ0uKKIgFLAVG4VZ53be6Z0NBHc46YgRhJbFocGFhbKlYIdp02hx74o7qwaVIfOY8U9egroNN5jI+Cuq1esMnqSKVVmiYtOnByyJ+y2AxLYKqUGWOibOl5kPIE1xdMIbE5l9Pll/MAABhBekf5cno2Lb1ae5qh8YMElBlDu5qtLGmRdymHT0oNRpcJJD6E7M7+cNPhtJX4lila1xSy2Ob7GgOucG3s8ZfBp21yQBxRvcKCmISBX0sYEu9gwIkJD38ZATjyfXs53T6eo9RVNuUt3J8L1UqjgiLA3C0+bUrb+8OroBM3Y4GD2631YWQkb6EdZ6g0t8jYyH6lIecDkovR3BSbpI9Vw2RJZ5ccdJXLAI88oZzga28xJBoflZpM2nJGmi2B+J3NsMkvfv/0hD8aQOniFkuzDlruUlbaiEASQadupSeTOsqE7h9nifDT8Te2I=
    branch: master
